# File name: App.py
#:kivy 1.10.0

<RedButton@Button>:
    background_color: 1,0,0,1
    color: 0,1,0,1
    font_size: 20

<Grid>:
    rows: 2
    spacing: 8
    padding: 8
    RedButton:
        id: save_button
        text: 'Save'
        size_hint: (0.2, 0.1)

    TextInput:
        id: url_input
        multiline: False
        font_size: 16

    RedButton:
        id: cancel_button
        text: 'Cancel'
